wip

diff --git a/.github/workflows/check-pr.yml b/.github/workflows/check-pr.yml
--- a/.github/workflows/check-pr.yml
+++ b/.github/workflows/check-pr.yml
@@ -17,14 +17,6 @@ jobs:
     env:
       JAVA_OPTS: -Dfile.encoding=UTF-8
       BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
-    services:
-      docker:
-        image: docker:latest
-        options: --privileged  # Required for Docker-in-Docker
-        volumes:
-          - /var/run/docker.sock:/var/run/docker.sock
-        ports:
-          - 2375:2375
     steps:
       - uses: actions/checkout@v4
       - uses: actions/setup-java@v4
@@ -47,7 +39,7 @@ jobs:
           wget https://binaries.soliditylang.org/linux-amd64/solc-linux-amd64-v0.8.29+commit.ab55807c -O /home/runner/.solc/v0.8.29/solc-static-linux
           echo "/home/runner/.solc" >> $GITHUB_PATH
           ln -sf /home/runner/.solc/v0.8.29/solc-static-linux /home/runner/.solc/solc
-          which solc || echo "Solc not found in PATH"
+      - run: which solc || echo "Solc not found in PATH"
       - uses: sbt/setup-sbt@v1
       - name: Run tests
         run: sbt -Dcc.it.max-parallel-suites=2 -Dlogback.test.level=DEBUG --batch "scalafmtCheck;test;docker;consensus-client-it/test"
