Chain contract: - Chain contract compatibility with older consensus client.
Tests:
- Unit tests work with simulate, fixed all exceptions in logs;
- Fixes for integration tests, including stabilization: units.AssetRegistryTestSuite, units.SyncingTestSuite, etc.

CI:
- Install solc 0.8.29, caching it and making available.

Local network:
- Works with the latest changes;
- Docker compose can use old images (deleting old containers first);
- deploy build fixes.

Other:
- Forge produces a lot of garbage logs;
- Removed besu mentioning from configs and docs.

diff --git a/.github/workflows/check-pr.yml b/.github/workflows/check-pr.yml
--- a/.github/workflows/check-pr.yml
+++ b/.github/workflows/check-pr.yml
@@ -26,10 +26,28 @@ jobs:
           java-version: '11'
           cache: 'sbt'
       - uses: foundry-rs/foundry-toolchain@v1
+      - name: Ensure solc directory exists
+        run: mkdir -p /home/runner/.solc
+      - name: Cache solc
+        id: cache-solc
+        uses: actions/cache@v4
+        with:
+          path: /home/runner/.solc
+          key: solc-v0.8.29
+          restore-keys: solc-
+      - name: Get solc
+        if: ${{ steps.cache-solc.outputs.cache-hit != 'true' }}
+        uses: pontem-network/get-solc@e187b20b402a33b6e0383a296445cbefdeeb5ba2 # 2022-07-08
+        with:
+          version: v0.8.29
+      - name: Make solc available
+        run: |
+          echo "/home/runner/.solc" >> $GITHUB_PATH
+          ln -sf /home/runner/.solc/v0.8.29/solc-static-linux /home/runner/.solc/solc
+          which solc || echo "Solc not found in PATH"
       - uses: sbt/setup-sbt@v1
       - name: Run tests
-        run: |
-          sbt --batch "test;docker;consensus-client-it/test"
+        run: sbt --batch "test;docker;consensus-client-it/test"
       - name: Archive logs
         uses: actions/upload-artifact@v4
         if: always()
